version: '3'

services:

  notebook_data_science_jupy:
    container_name: arxiv_jupyter_experiments
    image: maciomatheus/jupyter_notebook_data_science
    environment:
      JUPYTER_ENABLE_LAB: 1
      NB_UID: 10011
      GRANT_SUDO: "yes"
    user: root
    ports:
    - 8899:8888
    - 6008:6006
    - 5008:5000
    volumes:
    - ./:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
